"""AsciiDoctype Document Rendering Engine.

`asciidoctype.renderer` provides the primary rendering orchestrator
`AsciiDoctypeRenderer` for converting Abstract Semantic Graph (ASG) node trees
into HTML5 or XHTML representations via Chameleon ZPT templates.

*Features:*

* Support for multiple target formats (`html5`, `xhtml`).
* Layered template overrides with fallback chains.
* Polymorphic node dispatching for inline images and footnote references.
"""

import re
from pathlib import Path
from typing import Any, Callable, Dict, List, Literal, Optional, Sequence, Set, Tuple, Union

from chameleon import PageTemplate, PageTemplateLoader

from .exceptions import AsciiDoctypeRenderingError, AsciiDoctypeSecurityError
from .linter import audit_search_paths

DANGEROUS_URI_SCHEMES = ("javascript:", "vbscript:", "data:text/html")

TargetFormat = Literal["html5", "xhtml"]

HighlighterCallable = Callable[[str, str], Optional[str]]

_RE_COLS_SPLIT = re.compile(r"[,;]")
_RE_MULT_COL = re.compile(r"^(\d+)\*(.*)$")
_RE_NUM_COL = re.compile(r"(\d+(?:\.\d+)?)")


class AsciiDoctypeRenderer:
    """Renders AsciiDoc ASG nodes into HTML5 or XHTML string fragments.

    `AsciiDoctypeRenderer` manages template loading, format resolution, security audits,
    and recursive template dispatching for node structures generated by AsciiDoctrine.

    [attributes]
    `target_format` (str):: Target output format specification (`"html5"` or `"xhtml"`).
    `search_paths` (list[Path]):: Ordered list of template search directories.
    `strict` (bool):: Whether strict schema, template, and URI validation is enforced.
    `loader` (PageTemplateLoader):: Chameleon template loader initialized with search paths.
    `highlighter` (HighlighterCallable, optional):: Syntax highlighting callable.

    [source,python]
    ----
    renderer = AsciiDoctypeRenderer(target_format="html5", strict=True)
    html_output = renderer.render(node)
    ----
    """

    def __init__(
        self,
        target_format: Union[TargetFormat, str] = "html5",
        search_paths: Optional[Sequence[Union[str, Path]]] = None,
        strict: bool = False,
        validate_templates: bool = True,
        max_depth: int = 500,
        highlighter: Optional[HighlighterCallable] = None,
    ):
        """Initialize the rendering engine with format choices and template search paths.

        [parameters]
        `target_format` (str):: Output markup format specification (`"html5"` or `"xhtml"`).
                                Defaults to `"html5"`.
        `search_paths` (sequence[str | Path], optional):: Additional directory paths to search for
                                                          custom template overrides prior to core
                                                          fallback templates.
        `strict` (bool, optional):: If `True`, enforces strict node validation, raises security
                                    errors on unsafe templates and dangerous URIs, and disallows
                                    fallback container routing. Defaults to `False`.
        `validate_templates` (bool, optional):: Whether to audit custom template search paths
                                                for security and syntax flaws. Defaults to `True`.
        `max_depth` (int, optional):: Maximum recursive rendering depth before triggering stack
                                      protection. Defaults to `500`.
        `highlighter` (HighlighterCallable, optional):: Optional callable accepting `(code, lang)`
                                                        and returning highlighted markup or `None`.

        [raises]
        `ValueError`:: If `target_format` is not one of `"html5"` or `"xhtml"`.
        `AsciiDoctypeSecurityError`:: When `strict=True` and custom templates contain
                                      security issues.
        """

        self.target_format = target_format.lower()
        if self.target_format not in ("html5", "xhtml"):
            raise ValueError("target_format must be 'html5' or 'xhtml'")

        self.strict = strict
        self.max_depth = max_depth
        self.highlighter = highlighter

        base_dir = Path(__file__).parent.resolve()
        core_fallback = base_dir / "core_templates" / self.target_format

        custom_paths: List[Path] = [Path(p) for p in search_paths] if search_paths else []

        if validate_templates and custom_paths:
            audit_search_paths(custom_paths, strict=self.strict)

        self.search_paths: List[Path] = custom_paths + [core_fallback]

        self.loader = PageTemplateLoader(
            [str(p) for p in self.search_paths],
            default_extension=".html",
        )
        self._template_cache: Dict[Tuple[str, Optional[str], Optional[str]], PageTemplate] = {}

    def extract_text(self, node: Any) -> str:
        """Extract plain text representation from an ASG node or its inline hierarchy.

        [parameters]
        `node` (dict[str, Any] or any):: ASG node structure or child inline node.

        [returns]
        `str`:: The extracted plain text string.
        """
        if isinstance(node, str):
            return node
        if not isinstance(node, dict):
            return ""
        inlines = node.get("inlines")
        if isinstance(inlines, list) and inlines:
            return "".join(self.extract_text(child) for child in inlines)
        val = node.get("value")
        if isinstance(val, str):
            return val
        return ""

    def extract_col_widths(self, node: Dict[str, Any]) -> List[str]:
        """Extract and calculate proportional column widths from table columns or cols attribute.

        [parameters]
        `node` (dict[str, Any]):: ASG node representing a table block.

        [returns]
        `list[str]`:: A list of percentage strings (e.g. `["20%", "60%", "20%"]`),
                      or empty list if no valid column specifications are found.
        """
        if not isinstance(node, dict):
            return []

        # 1. Check for structured columns collection (spec-compliant ASG)
        columns = node.get("columns")
        if isinstance(columns, list) and columns:
            raw_widths: List[float] = []
            has_raw = False
            for col in columns:
                if isinstance(col, dict):
                    w = col.get("width")
                    if isinstance(w, str) and w.endswith("%"):
                        try:
                            raw_widths.append(float(w[:-1].strip()))
                            has_raw = True
                            continue
                        except ValueError:
                            pass
                    elif isinstance(w, (int, float)):
                        raw_widths.append(float(w))
                        has_raw = True
                        continue
                raw_widths.append(1.0)
            if has_raw and sum(raw_widths) > 0:
                total = sum(raw_widths)
                return [f"{round((w / total) * 100, 4):g}%" for w in raw_widths]

        # 2. Fallback: Parse attributes.cols string
        attributes = node.get("attributes")
        cols_str = ""
        if isinstance(attributes, dict):
            cols_str = str(attributes.get("cols") or "").strip()
        if not cols_str:
            cols_str = str(node.get("cols") or "").strip()
        if not cols_str:
            return []

        parts = [p.strip() for p in _RE_COLS_SPLIT.split(cols_str) if p.strip()]
        if not parts:
            return []

        raw_parts: List[float] = []
        for part in parts:
            mult_match = _RE_MULT_COL.match(part)
            if mult_match:
                count = int(mult_match.group(1))
                rest = mult_match.group(2).strip()
                num_match = _RE_NUM_COL.search(rest)
                w = float(num_match.group(1)) if num_match else 1.0
                raw_parts.extend([w] * count)
            else:
                num_match = _RE_NUM_COL.search(part)
                w = float(num_match.group(1)) if num_match else 1.0
                raw_parts.append(w)

        total_sum = sum(raw_parts)
        if total_sum <= 0:
            return []

        return [f"{round((w / total_sum) * 100, 4):g}%" for w in raw_parts]

    def highlight_code(
        self, node: Dict[str, Any], ctx: Optional[Dict[str, Any]] = None
    ) -> Optional[str]:
        """Highlight code content within an ASG node using the configured highlighter callable.

        [parameters]
        `node` (dict[str, Any]):: ASG node representing a source or listing block.
        `ctx` (dict[str, Any], optional):: Contextual dictionary passed down the
                                           rendering pipeline.

        [returns]
        `str` or `None`:: The highlighted markup if a highlighter callable is configured
                          and successfully produces output, otherwise `None`.
        """
        if self.highlighter is None:
            return None
        code = self.extract_text(node)
        attributes = node.get("attributes")
        lang = ""
        if isinstance(attributes, dict):
            lang = attributes.get("language") or attributes.get("lang") or ""
        if not lang:
            lang = node.get("language") or ""
        try:
            return self.highlighter(code, str(lang))
        except Exception:
            return None

    def render(self, node: Dict[str, Any], context: Optional[Dict[str, Any]] = None) -> str:
        """Central dispatch router for resolving and rendering ASG nodes recursively.

        Evaluates polymorphic node characteristics to determine appropriate template
        candidates and executes the matching Chameleon template.

        [parameters]
        `node` (dict[str, Any]):: The ASG node dictionary containing at least a `"name"` key.
        `context` (dict[str, Any], optional):: Contextual variables passed down the rendering
                                               pipeline. Defaults to `None`.

        [returns]
        `str`:: Rendered HTML5 or XHTML string output.

        [raises]
        `TypeError`:: If `node` is not a `dict` or does not contain a `"name"` attribute.
        `AsciiDoctypeRenderingError`:: If template lookup or template execution fails.
        `AsciiDoctypeSecurityError`:: If dangerous URI schemes are used under `strict=True`.
        """
        if not isinstance(node, dict) or "name" not in node:
            raise TypeError("Invalid node structure passed to rendering processor.")

        ctx = dict(context) if context else {}

        # Recursion depth and cycle protection
        depth: int = ctx.get("_depth", 0) + 1
        visited: Set[int] = set(ctx.get("_visited", ()))

        if depth > self.max_depth or id(node) in visited:
            raise AsciiDoctypeRenderingError(
                "Recursion depth limit exceeded / Cycle detected in ASG structure."
            )

        visited.add(id(node))
        ctx["_depth"] = depth
        ctx["_visited"] = visited

        # Security check: URI scheme validation for ref and media nodes
        effective_node = node
        target_uri = node.get("target") or node.get("src")
        if isinstance(target_uri, str):
            clean_uri = target_uri.strip().lower()
            if any(clean_uri.startswith(scheme) for scheme in DANGEROUS_URI_SCHEMES):
                if self.strict:
                    raise AsciiDoctypeSecurityError(
                        f"Strict security violation: dangerous URI scheme detected: '{target_uri}'"
                    )
                # Sanitize to empty string
                effective_node = dict(node)
                if "target" in effective_node:
                    effective_node["target"] = ""
                if "src" in effective_node:
                    effective_node["src"] = ""

        node_name = effective_node["name"]
        node_type = effective_node.get("type")
        node_variant = effective_node.get("variant")
        cache_key = (
            str(node_name),
            str(node_type) if node_type is not None else None,
            str(node_variant) if node_variant is not None else None,
        )

        try:
            template = self._template_cache.get(cache_key)
            if template is None:
                candidates: List[str]
                if node_name == "image" and node_type == "inline":
                    candidates = ["image_inline.html", "image.html"]
                elif node_name == "ref" and node_variant == "footnote":
                    candidates = ["footnote.html", "ref.html"]
                elif node_name == "source":
                    candidates = ["source.html", "listing.html"]
                else:
                    candidates = [f"{node_name}.html"]

                for candidate in candidates:
                    try:
                        template = self.loader[candidate]
                        break
                    except ValueError:
                        continue

                if template is None:
                    if self.strict:
                        raise AsciiDoctypeRenderingError(
                            f"Strict mode violation: unknown ASG node type '{node_name}' "
                            f"has no registered template."
                        )
                    template = self.loader["fallback_container.html"]

                self._template_cache[cache_key] = template

            res: str = template(node=effective_node, renderer=self, ctx=ctx)
            return res
        except (AsciiDoctypeRenderingError, AsciiDoctypeSecurityError):
            raise
        except Exception as err:
            node_id = effective_node.get("name", "unknown")
            raise AsciiDoctypeRenderingError(
                f"Critical rendering failure processing structural node entity: '{node_id}' "
                f"Target Specification Pipeline: [{self.target_format}]. Base Error: {err!s}"
            ) from err


def render(
    node: Dict[str, Any],
    target_format: Union[TargetFormat, str] = "html5",
    search_paths: Optional[Sequence[Union[str, Path]]] = None,
    strict: bool = False,
    validate_templates: bool = True,
    max_depth: int = 500,
    highlighter: Optional[HighlighterCallable] = None,
    context: Optional[Dict[str, Any]] = None,
) -> str:
    """Convenience function to render an ASG node into HTML5 or XHTML.

    [parameters]
    `node` (dict[str, Any]):: The ASG node dictionary to render.
    `target_format` (str):: Output markup format (`"html5"` or `"xhtml"`). Defaults to `"html5"`.
    `search_paths` (sequence[str | Path], optional):: Additional directory paths to search for
                                                      custom templates. Defaults to `None`.
    `strict` (bool, optional):: If `True`, enforces strict validation. Defaults to `False`.
    `validate_templates` (bool, optional):: Whether to audit custom search paths.
                                            Defaults to `True`.
    `max_depth` (int, optional):: Maximum recursive rendering depth. Defaults to `500`.
    `highlighter` (HighlighterCallable, optional):: Syntax highlighting callable.
                                                    Defaults to `None`.
    `context` (dict[str, Any], optional):: Context variables dictionary. Defaults to `None`.

    [returns]
    `str`:: Rendered HTML5 or XHTML string output.

    [source,python]
    ----
    import asciidoctype

    html = asciidoctype.render(asg_node, target_format="html5")
    ----
    """
    renderer = AsciiDoctypeRenderer(
        target_format=target_format,
        search_paths=search_paths,
        strict=strict,
        validate_templates=validate_templates,
        max_depth=max_depth,
        highlighter=highlighter,
    )
    return renderer.render(node, context=context)
